### ISSUE TITLE
Parse unquoted string with less strictly in block sequence

### ISSUE THREAD

**Issue by Him188** [Him188/yamlkt#14]
Test `nested descriptor block sequence5` and `nested descriptor block sequence6` should succeed.

YAML:
```yaml
- 
  - sss
   ssss
  - x
   - x
  - p: x
    y: x
```
JSON:
```json
[
  [
    "sss ssss",
    "x - x",
    {
      "p": "x",
      "y": "x"
    }
  ]
]
```
