### ISSUE TITLE
Serialize / Deserialize comments through `Commentable<Any>`

### ISSUE THREAD

**Issue by RinOrz** [Him188/yamlkt#35]
I propose to add a new object instead of using an annotation to decode / encoding comments, so it can support comments for each element? 

**proposal**
```kotlin
data class Commentable<T>(val comment: String, val value: T)
```

**yml**:
```yml
# people's rating
rank: 80
foods: # list declaration
  # need a pizza
  pizza: true
takeout: true
```

**kotlin**:
```kotlin
@Serializable
data class Test(
  val rank: Commentable<Int>,
  val foods: List<Commentable<String>>,
  val takeout: Commentable<Boolean>,
)
```

Also, it seems impossible to serialize comments as objects at present, or do I miss something?
