### ISSUE TITLE
The property name was incorrectly resolved if the name has colon

### ISSUE THREAD

**Issue by RinOrz** [Him188/yamlkt#36]
Currently, If there is a colon in the name, it will directly resolve the string on the left of the colon as the name, and the string on the right as the value. Ideally, it should parse the last colon of the line.

```yaml
com.google.guava:guava:
  versions:
    - 99.0-SNAPSHOT
    - 100.0
    - 101.1-SNAPSHOT
    - 102.1-SNAPSHOT
  rejectSnapshot: false
```

Expected:
```kotlin
MapEntry(key = com.google.guava.guava, value = Map<String, Any>)
```

But Actual:
```kotlin
MapEntry(key = com.google.guava, value = guava)
```
