### ISSUE TITLE
deserializer says there's a missing colon between key and value when it exists

### ISSUE THREAD

**Issue by rmullin7286** [Him188/yamlkt#58]
Sample input. This was generated by printing out the encoded yaml from a dataclass. I also ran it through a yaml linter to verify that it was correct:
```
recipe: 
  name: foo
  author: ryan
  description: desc
  instructions: 
    - this
    - that
    - then
  ingredients: 
    - name: foo
      measurement: 
        amount: 1.0
        unit: UNIT
pantryItems: 
  - name: pantry
    nutritionInfo: 
      caloriesPer: 1
      unit: UNIT
```
Error:
```
Uncaught Kotlin exception: net.mamoe.yamlkt.YamlDecodingException: There must be a COLON between class key and value but found null for 'me.rmullin.shared.RecipeFile'
./test.yaml
          ^ at line 1, column 12

```
